/*
 * generated by Xtext
 */
package arden.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArdenSyntaxRuntimeModule extends arden.xtext.AbstractArdenSyntaxRuntimeModule {

}
